name: Mark stale issues and pull requests

on:
  schedule:
  - cron: '00 5 * * *'

jobs:
  stale:

    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write

    steps:
    - uses: actions/stale@v3
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        exempt-issue-labels: 'backlog,epic'
        stale-issue-message: 'Пожалуйста, уточните что осталось доделать в этой задаче и сколько времени этой займет?'
        stale-pr-message: 'В запрое на слияние нет активности. Пожалуйста, напишите в общий чат о необходимости проверить этот запрос.'
        stale-issue-label: 'no-issue-activity'
        stale-pr-label: 'no-pr-activity'
        days-before-issue-stale: 7
        days-before-pr-stale: 1
        days-before-issue-close: 7
        days-before-pr-close: 1
